LOAD DATA
INFILE "D:\CASH_IBFT\LOADER\FILES\BALINQ_1LINK.TXT"
TRUNCATE
INTO TABLE ONELINKMNET.TBL_BALINQ_1LINK
(ID "SEQ_IBFT_1LINK.nextval",
SETTLEMENT_DATE POSITION(11:14) char,
PAN POSITION(29:48) char,
AMOUNT POSITION (49:60) char,
FEE_CHARGES POSITION (61:69) char,
TRN_TIME POSITION (70:79) CHAR,
STAN POSITION (80:85) CHAR,
TERMINAL POSITION (86:89) CHAR)